[package]
name = "sound-player"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
iocraft = "0.8.4"
rodio = "0.22.2"
rusqlite = { version = "0.33", features = ["bundled"] }
rustfft = "6.4.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
smol = "2.0.2"
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"

[dev-dependencies]
crossterm = "0.29.0"
futures = "0.3.34"
